### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by kukulogy** [wuzhouhui/ngx-hdfs#3]
Hi, 

I like to asked what library are you using in compiling this module? 

I can't get the `# make` works since I have this error.

> /home/hadoop/nginx-1.8.0/ngx/ngx-hdfs/ngx_http_hdfs_module.c:9:10: fatal error: 'error.h' file not found
> # include <error.h>
> 
> ```
>      ^
> ```
> 
> 1 error generated.
> **\* Error code 1
> Stop.
> make[1]: stopped in /usr/home/hadoop/nginx-1.8.0
> **\* Error code 1
> Stop.
> make: stopped in /usr/home/hadoop/nginx-1.8.0 

I'm using FreeBSD10 and all the other requirements you've mentioned in the README. Thanks!

**Comment by wuzhouhui** [comment]
My OS is ubuntu14.04 32bit, and error.h is a standard header file, it belongs to GNU C library.
